# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikesPage',
            fields=[
                ('corepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CorePage')),
                ('old_url', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.corepage',),
        ),
    ]
